const appConfig = {
  appName: 'Innobox',
  apiUrl:
    'http://ec2-35-154-205-221.ap-south-1.compute.amazonaws.com:8080/api/',
  imageUrl: 'http://ec2-35-154-205-221.ap-south-1.compute.amazonaws.com:8080',
  routes: {
    career: 'career',
    contactus: 'contact-us',
    whyus: 'why-us',
    home: '',
    gryphion: 'gryphion',
    fiveg: '5g',
    lab: 'lab',
    greyn: 'greyn',
    mobileapps: 'mobile-apps',
    recentworks: 'recent-work',
    mainservice: 'services',
    networkstack: 'network-stack',
    fivegsolution: '5g-solution',
    connectivity: 'connectivity',
    linuxandroid: 'linux-and-android',
    testingautomation: 'testing-automation',
    wirelesstechnology: 'wireless-technologies',
    wifisolution: 'wifi-solution',
    clouddesktop: 'cloud-desktop-application',
    iot: 'iot',
    ai: 'atrificial-intelligence',
    certification: 'certification',
    mobility: 'mobility',
    mobileapplication: 'mobile-application',
    computervision: 'computer-vision',
  },
};
export default appConfig;
