const appConfig = {
  appName: 'Innobox',
  apiUrl:
    'http://ec2-35-154-205-221.ap-south-1.compute.amazonaws.com:8080/api/web/',
    apiUrl1:
    'http://ec2-35-154-205-221.ap-south-1.compute.amazonaws.com:8080/api/',
  imageUrl: 'http://ec2-35-154-205-221.ap-south-1.compute.amazonaws.com:8080',


  routes: {
    career: 'career',
    contactus: 'contact-us',
    whyus: 'why-us',
    home: 'home',
    def:'',
   
    // gryphion: 'gryphion',
    recentworkcat: 'recent-work-category',
    fiveg: '5g',
    lab: 'lab',
    greyn: 'greyn',
    mobileapps: 'mobile-apps',
    recentworks: 'recent-work',
    mainservice: 'services',
    service: 'service',
    // networkstack: 'network-stack',
    singleservice: 'service',
    fivegsolution: '5g-solution',
    connectivity: 'connectivity',
    linuxandroid: 'linux-and-android',
    testingautomation: 'testing-automation',
    wirelesstechnology: 'wireless-technologies',
    wifisolution: 'wifi-solution',
    clouddesktop: 'cloud-desktop-application',
    iot: 'iot',
    ai: 'atrificial-intelligence',
    certification: 'certification',
    mobility: 'mobility',
    mobileapplication: 'mobile-application',
    computervision: 'computer-vision',
    successstory: 'success-stories',
    autotestapp: 'automation-test-application',
    securityiot: 'security-and-surveillance-iiot',
    iniotplat: 'industrial-iot-platform',
    latestwork: 'latest-work',
    sihomerouter: 'secure-and-intelligent-home-router',
    multibandfiveg: 'multiband-5g-gateway',
    aboutus: 'about-us',
    terms: 'terms-and-condition',
    legal: 'legal',
  },
};
export default appConfig;
